name: Cross-Post to Dev.to
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 必须设置为 0，否则插件找不到文件历史

      - name: Publish to Dev.to
        uses: sinedied/publish-devto@v2
        with:
          devto_key: ${{ secrets.DEVTO_API_KEYS }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # 删掉了报错的 base_url
